/**
 * Minimal Seed Script — END-TO-END TESTING ONLY
 * ----------------------------------------------------------------------------
 * Populates the bare minimum needed to log in and exercise the system with
 * REAL data from the desktop agent (no fake signals, no fake activity logs,
 * no fake risk scores). Everything else — attendance signals, productivity
 * scores, alerts — must be generated by actually using the product.
 *
 * Creates:
 *   - 1 Super Admin (system-level, no organization)
 *   - 1 Organization: "Cravix" (approved + active)
 *   - 1 Org Admin user
 *   - 1 HR Admin user
 *   - 1 Manager  (user + employee profile)
 *   - 2 Employees (user + employee profile, both reporting to the manager)
 *   - 1 Department: "Engineering"
 *
 * Run: npm run seed
 */
require('dotenv').config();
const mongoose = require('mongoose');
const { connectDB } = require('../config/db');
const User = require('../models/User');
const Organization = require('../models/Organization');
const Department = require('../models/Department');
const Employee = require('../models/Employee');
const Signal = require('../models/Signal');
const PulseSurvey = require('../models/PulseSurvey');
const Plan = require('../models/Plan');
const RiskAssessment = require('../models/RiskAssessment');
const Notification = require('../models/Notification');
const ActivityLog = require('../models/ActivityLog');
const ActivitySession = require('../models/ActivitySession');
const ActivityEvent = require('../models/ActivityEvent');
const ScreenshotLog = require('../models/ScreenshotLog');
const AppUsageLog = require('../models/AppUsageLog');
const ProductivityScore = require('../models/ProductivityScore');
const Alert = require('../models/Alert');
const Task = require('../models/Task');
const Intervention = require('../models/Intervention');
const { ORGANIZATION_APPROVAL_STATUS, ROLES } = require('../config/constants');

async function clear() {
  await Promise.all([
    User.deleteMany({}),
    Organization.deleteMany({}),
    Department.deleteMany({}),
    Employee.deleteMany({}),
    Signal.deleteMany({}),
    PulseSurvey.deleteMany({}),
    Plan.deleteMany({}),
    RiskAssessment.deleteMany({}),
    Notification.deleteMany({}),
    ActivityLog.deleteMany({}),
    ActivitySession.deleteMany({}),
    ActivityEvent.deleteMany({}),
    ScreenshotLog.deleteMany({}),
    AppUsageLog.deleteMany({}),
    ProductivityScore.deleteMany({}),
    Alert.deleteMany({}),
    Task.deleteMany({}),
    Intervention.deleteMany({}),
  ]);
}

async function run() {
  await connectDB();
  await clear();
  console.log('[seed] cleared all collections');

  // 1) Super Admin — system-wide, no organizationId
  const superAdmin = await User.create({
    name: 'RetainIQ Super Admin',
    email: 'super@retainiq.dev',
    passwordHash: await User.hashPassword('SuperPass!234'),
    role: ROLES.SUPER_ADMIN,
  });

  // 2) Organization — Cravix (approved + active so login works immediately)
  const org = await Organization.create({
    name: 'Cravix',
    domain: 'cravix.test',
    industry: 'Software',
    size: '11-50',
    plan: 'growth',
    isActive: true,
    approvalStatus: ORGANIZATION_APPROVAL_STATUS.APPROVED,
    approvedBy: superAdmin._id,
    approvedAt: new Date(),
  });
  await Plan.create({ organizationId: org._id, plan: 'growth', seats: 10 });

  // 3) One department so dropdowns aren't empty
  const engineering = await Department.create({
    organizationId: org._id,
    name: 'Engineering',
  });

  // 4a) Org Admin — tenant owner, manages org-level settings, billing, users.
  //     No employee profile (admin is a system role, not part of workforce).
  await User.create({
    organizationId: org._id,
    name: 'Anita Admin',
    email: 'admin@cravix.test',
    passwordHash: await User.hashPassword('AdminPass!234'),
    role: ROLES.ORG_ADMIN,
  });

  // 4b) HR Admin — no employee profile (HR is a system user, not workforce)
  await User.create({
    organizationId: org._id,
    name: 'Hari HR',
    email: 'hr@cravix.test',
    passwordHash: await User.hashPassword('HrPass!234'),
    role: ROLES.HR_ADMIN,
  });

  // 5) Manager — needs BOTH an Employee profile (so they show up in reporting
  //    tree + can run the desktop agent on themselves) AND a User account.
  const managerEmployee = await Employee.create({
    organizationId: org._id,
    employeeCode: 'CRX-0001',
    name: 'Meera Manager',
    email: 'manager@cravix.test',
    designation: 'Engineering Manager',
    departmentId: engineering._id,
    employmentType: 'full_time',
    workMode: 'hybrid',
    joiningDate: new Date('2024-01-15'),
  });
  await User.create({
    organizationId: org._id,
    employeeId: managerEmployee._id,
    name: managerEmployee.name,
    email: managerEmployee.email,
    passwordHash: await User.hashPassword('ManagerPass!234'),
    role: ROLES.MANAGER,
  });

  // 6) Two Employees reporting to the manager
  const employeesSpec = [
    {
      code: 'CRX-0002',
      name: 'Aman Employee',
      email: 'emp1@cravix.test',
      designation: 'Software Engineer',
      workMode: 'remote',
      joiningDate: new Date('2024-06-01'),
    },
    {
      code: 'CRX-0003',
      name: 'Bhavna Employee',
      email: 'emp2@cravix.test',
      designation: 'Software Engineer',
      workMode: 'office',
      joiningDate: new Date('2025-02-10'),
    },
  ];

  for (const spec of employeesSpec) {
    const emp = await Employee.create({
      organizationId: org._id,
      employeeCode: spec.code,
      name: spec.name,
      email: spec.email,
      designation: spec.designation,
      departmentId: engineering._id,
      reportingManagerId: managerEmployee._id,
      employmentType: 'full_time',
      workMode: spec.workMode,
      joiningDate: spec.joiningDate,
    });
    await User.create({
      organizationId: org._id,
      employeeId: emp._id,
      name: emp.name,
      email: emp.email,
      passwordHash: await User.hashPassword('EmployeePass!234'),
      role: ROLES.EMPLOYEE,
    });
  }

  console.log('[seed] complete — clean slate for end-to-end testing\n');
  console.log('  Super Admin   super@retainiq.dev      SuperPass!234');
  console.log('  Org Admin     admin@cravix.test       AdminPass!234');
  console.log('  HR Admin      hr@cravix.test          HrPass!234');
  console.log('  Manager       manager@cravix.test     ManagerPass!234');
  console.log('  Employee 1    emp1@cravix.test        EmployeePass!234');
  console.log('  Employee 2    emp2@cravix.test        EmployeePass!234');
  console.log('\n  No signals, no activity, no risk scores — generate them by using the app.');

  await mongoose.disconnect();
}

run().catch((err) => { console.error(err); process.exit(1); });
